### ISSUE TITLE
멀티 서버 선택 기능 TODO 

### ISSUE THREAD

**Issue by kranian** [scouter-contrib/scouter-paper#258]
멀티 서버 기능  검토 리스트 
-  Control 
    -  Select Target Object
        -  [x] SERVER NAVIGATOR 
              - [x] SELECT, APPLY
        -  [x] PRESET MANAGER 
              - [x] SAVE , LOAD
-  Paper 
    -  Real Time/Search 
         -  [x] Graph Chart(Line,Stack,Area)
         -  [x] XLog
              -  [x] Profile List
              -  [x] Profile Step
-  Topology 
    -  [x] 현재 서버ID 기준 오브젝트 대상 정보 가져오기 
    -  [x] 현재 서버ID 기준 토폴로지 위치 설정 정보
